name: 'Release creator'
description: 'Create release base on title of PR'
inputs:
  org-github-token:
    description: 'Org github token'
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Title Check
      id: title-check
      uses: zapay-pagamentos/zpy-platform-k8s-check-pr-title-action@main
      with:
        org_github_token: ${{ inputs.org-github-token }}
    - name: Validate version
      id: validate-version
      uses: zapay-pagamentos/zpy-platform-k8s-validate-version-action@v2
    - name: Add tag and make a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.org-github-token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.validate-version.outputs.versionCandidate }}
        release_name: ${{ steps.validate-version.outputs.versionCandidate }}
        draft: false
        prerelease: false
    
