apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: zpy-platform-k8s-create-release-action
  description: Github Action to create release
  annotations:
    github.com/project-slug: zapay-pagamentos/zpy-platform-k8s-create-release-action
spec:
  type: library
  lifecycle: production
  owner: darrell
